ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "subscriptionPlan" TEXT NOT NULL DEFAULT 'FREE',
ADD COLUMN IF NOT EXISTS "subscriptionStatus" TEXT NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE "User"
ALTER COLUMN "subscriptionPlan" SET DEFAULT 'FREE',
ALTER COLUMN "subscriptionStatus" SET DEFAULT 'ACTIVE';

ALTER TABLE "Report"
ADD COLUMN IF NOT EXISTS "reportType" TEXT NOT NULL DEFAULT 'RESIDENTIAL',
ADD COLUMN IF NOT EXISTS "city" TEXT,
ADD COLUMN IF NOT EXISTS "district" TEXT,
ADD COLUMN IF NOT EXISTS "neighborhood" TEXT,
ADD COLUMN IF NOT EXISTS "tkgmCity" TEXT,
ADD COLUMN IF NOT EXISTS "tkgmDistrict" TEXT,
ADD COLUMN IF NOT EXISTS "tkgmNeighborhood" TEXT,
ADD COLUMN IF NOT EXISTS "blockNo" TEXT,
ADD COLUMN IF NOT EXISTS "parcelNo" TEXT,
ADD COLUMN IF NOT EXISTS "landArea" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "landQuality" TEXT,
ADD COLUMN IF NOT EXISTS "planInfo" TEXT;

ALTER TABLE "Property"
ADD COLUMN IF NOT EXISTS "tkgmCity" TEXT,
ADD COLUMN IF NOT EXISTS "tkgmDistrict" TEXT,
ADD COLUMN IF NOT EXISTS "tkgmNeighborhood" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "User_phone_key" ON "User"("phone");
